# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76791a64e89920590332b14d7e3e359a2357db100f3c720e482532c4aa0e7993c00c9ec45eb0afe038c969927ebf67de25416bc979523427f3ebc9494b6dcdc

test:
  secret_key_base: ebdfb62729c21fb08eccd096052d9b5f9a646d24eaca875a375ca5226d684076ee9ebb67d53952b82f85926d91123df9bc3fa3633d9ceb6d5a92e782de806ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
